name: cpacspy_env

channels:
  - dlr-sc
  - defaults
dependencies:
  
  - flake8
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.7
  - pytest
  - pytest-cov
  - setuptools
  # - tigl3=3.2.2
  - cpacscreator=0.1
  - tixi3=3.0.3
  - wheel
 
  - pip:
    - ambiance