name: cpacspy_env
channels:
  - dlr-sc
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.7
  - pytest
  - setuptools
  - tigl3=3.2.1
  - tixi3=3.1.1
  - wheel
 
  - pip:
    - ambiance