name: cpacspy_env

channels:
  - dlr-sc
  - defaults

dependencies:
  
  - python=3.7
  - numpy
  - pandas
  - pip
  - setuptools
  - wheel
  - matplotlib
  - plotly
  - ipywidgets>=7.6
  # - tigl3=3.2.2
  - cpacscreator=0.1
  - tixi3=3.0.3

  # CI and test
  - black
  - flake8
  - pytest
  - pytest-cov
  
  - pip:
    - ambiance