# This file lists external packages required to run and develop cpacspy.
#
# * Only top-level requirements are listed here.
# You can use this file to set up a Conda environment:
#
# conda env create -f environment.yml
#
# See also: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

name: cpacspy_env_2

channels:
  - conda-forge
  - defaults
  - dlr-sc

dependencies:
  
  - ambiance>=1.3.0
  - cpacscreator=0.1
  - matplotlib=3.5.0
  - numpy=1.21.2
  - pandas=1.3.4
  - pip=21.2.2
  - plotly=5.1.0
  - python=3.8
  - scipy=1.7.3
  - setuptools=58.0.4
  - tixi3=3.0.3
  - wheel=0.37.0
 
  # CI and test
  - black>=22.1.0
  - coverage=5.5
  - flake8>=4.0.1
  - pytest=6.2.5
  - pytest-cov=3.0.0
  
