# This file lists external packages required to run and develop cpacspy.
#
# * Only top-level requirements are listed here.
# You can use this file to set up a Conda environment:
#
# conda env create -f environment.yml
#
# See also: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

name: cpacspy_env

channels:
  - conda-forge
  - defaults
  - dlr-sc

dependencies:

  - python=3.11.11
  - ambiance=1.3.1
  - cpacscreator>=0.2.0
  - matplotlib=3.9.1
  - numpy=2.2.4
  - pandas=2.2.3
  - pip=25.0.1
  - plotly=6.0.1
  - scipy=1.15.2
  - setuptools=78.1.0
  - wheel=0.45.1

  # CI and test
  - black=25.1.0
  - coverage=7.8.0
  - flake8=7.2.0
  - pytest=8.3.5
  - pytest-cov=6.1.1
