name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: cpacspy_env
        use-mamba: true

    - name: Set cache date # With that, cache will be updated every day
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - uses: actions/cache@v3
      with:
        path: /usr/share/miniconda3/envs/cpacspy_env
        key: ubuntu-latest-conda-${{ env.DATE }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      id: cache

    - name: Update environment
      run: mamba env update -n cpacspy_env -f environment.yml
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Install cpacspy with pip
      shell: bash -l {0}
      run: pip install -e .

    - name: Run flake8
      shell: bash -l {0}
      run: flake8

    - name: Run pytest
      shell: bash -l {0}
      run: pytest -v --cov=src/ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        fail_ci_if_error: false
        verbose: true
