name: Pytest windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        environment-file: environment.yml
        auto-update-conda: false
        python-version: 3.7

    - name: Pip install
      shell: bash -l {0}
      run: pip install -e .

    - name: Run pytest
      run: pytest -v --cov=src\ --cov-report=xml